Mega typo fix
MLDEG/Ragnamod_VII pull request #128
Opened 2024-05-18 14:22 UTC by SNEAXIII

Here some typo fixes, I hope you will enjoy it ^^

2024-06-10 09:18 UTC, Leclowndu93150 commented
looks cool

2024-07-12 15:55 UTC, ItsAMemeMario requested changes

2024-07-12 15:55 UTC, ItsAMemeMario commented on config/ftbquests/quests/chapters/ars_nouveau.snbt
> +			description: ["This is the last mage tunic in Ars Nouveau, It's used in the end game armor."]
Use a period because they're separate sentences.

```
"This is the last mage tunic in Ars Nouveau. It's used in the end game armor."
```

2024-07-12 15:55 UTC, ItsAMemeMario commented on config/ftbquests/quests/chapters/end_game.snbt
> +			description: ["Craft the Death armor, It's used in the End Game armor."]
Use a period

2024-07-12 15:55 UTC, ItsAMemeMario commented on config/ftbquests/quests/chapters/end_game.snbt
> +			description: ["Craft the Conquest armor, It's used in the End Game armor."]
Period

2024-07-12 15:55 UTC, ItsAMemeMario commented on config/ftbquests/quests/chapters/end_game.snbt
> +			description: ["Craft the Famine armor, It's used in the End Game armor."]
Period

2024-07-12 15:55 UTC, ItsAMemeMario commented on config/ftbquests/quests/chapters/end_game.snbt
> +			description: ["Craft the War armor, It's used in the End Game armor."]
Period

2024-07-13 00:21 UTC, Leclowndu93150 commented
period

2024-09-20 21:55 UTC, SNEAXIII commented on config/ftbquests/quests/chapters/end_game.snbt
> +			description: ["Craft the Death armor, It's used in the End Game armor."]
Hi, I am sorry, I don't understand where :(

2024-09-20 22:10 UTC, SNEAXIII commented
Salut @MLDEG, du nouveau ? :)

2024-09-21 11:03 UTC, Leclowndu93150 commented
faudrait lui demander la prochaine fois qu'il steam

2025-11-17 16:51 UTC, closed without merging